source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '7.0'
target :demo do

pod 'AppTemplateLib', :podspec => 'https://github.com/linzhiman/AppTemplateLib/blob/master/AppTemplateLib.podspec?raw=1'

end

